// OpsConductor Mock Data for v1

export type AgentStatus = "running" | "idle" | "paused" | "error"
export type ApprovalStatus = "pending" | "approved" | "rejected" | "auto-executed"
export type RiskLevel = "low" | "medium" | "high"
export type EventStatus = "success" | "failed" | "pending" | "running"

export interface Agent {
  id: string
  name: string
  role: string
  status: AgentStatus
  connectedApps: string[]
  actionsThisWeek: number
  costThisMonth: number
  lastActive: string
  createdAt: string
  totalActions: number
  totalCost: number
  sparklineData: number[]
  nextAction?: string
  nextActionTime?: string
}

export interface Approval {
  id: string
  agentId: string
  agentName: string
  agentRole: string
  riskLevel: RiskLevel
  status: ApprovalStatus
  actionDescription: string
  draftContent?: string
  draftSubject?: string
  targetEntity: string
  targetType: string
  timestamp: string
  app: string
}

export interface ActivityEvent {
  id: string
  agentId: string
  agentName: string
  app: string
  action: string
  target: string
  status: EventStatus
  cost: number
  timestamp: string
  reasoning?: string
}

export interface Integration {
  id: string
  name: string
  icon: string
  category: string
  connected: boolean
  status?: "live" | "expiring" | "disconnected"
  lastSynced?: string
  agentCount?: number
}

export const agents: Agent[] = [
  {
    id: "agent-1",
    name: "Lead Nurturer",
    role: "Lead Nurturer",
    status: "running",
    connectedApps: ["HubSpot", "Gmail", "Slack"],
    actionsThisWeek: 47,
    costThisMonth: 2.34,
    lastActive: "2 min ago",
    createdAt: "2026-01-15",
    totalActions: 1284,
    totalCost: 18.92,
    sparklineData: [5, 8, 12, 7, 9, 15, 11],
    nextAction: "Follow up with Sarah Chen",
    nextActionTime: "In 2 hours",
  },
  {
    id: "agent-2",
    name: "Churn Rescue",
    role: "Churn Rescue",
    status: "running",
    connectedApps: ["Stripe", "HubSpot", "Gmail"],
    actionsThisWeek: 23,
    costThisMonth: 1.87,
    lastActive: "15 min ago",
    createdAt: "2026-01-20",
    totalActions: 567,
    totalCost: 9.45,
    sparklineData: [3, 5, 2, 8, 4, 6, 3],
    nextAction: "Check Acme Corp usage",
    nextActionTime: "In 45 min",
  },
  {
    id: "agent-3",
    name: "Invoice Chaser",
    role: "Invoice Chaser",
    status: "idle",
    connectedApps: ["Stripe", "Gmail", "Slack"],
    actionsThisWeek: 8,
    costThisMonth: 0.56,
    lastActive: "3 hours ago",
    createdAt: "2026-02-01",
    totalActions: 234,
    totalCost: 4.12,
    sparklineData: [1, 2, 1, 0, 3, 1, 0],
    nextAction: "Send reminder to Globex",
    nextActionTime: "Tomorrow 9am",
  },
  {
    id: "agent-4",
    name: "Welcome Bot",
    role: "New User Welcome",
    status: "paused",
    connectedApps: ["Slack", "Notion"],
    actionsThisWeek: 0,
    costThisMonth: 0,
    lastActive: "2 days ago",
    createdAt: "2026-02-10",
    totalActions: 89,
    totalCost: 1.23,
    sparklineData: [4, 2, 0, 0, 0, 0, 0],
  },
  {
    id: "agent-5",
    name: "Deal Nudger",
    role: "Deal Stage Nudge",
    status: "error",
    connectedApps: ["HubSpot", "Slack"],
    actionsThisWeek: 3,
    costThisMonth: 0.12,
    lastActive: "1 hour ago",
    createdAt: "2026-02-15",
    totalActions: 156,
    totalCost: 2.78,
    sparklineData: [2, 4, 6, 3, 1, 0, 3],
  },
  {
    id: "agent-6",
    name: "Content Writer",
    role: "Content Generation",
    status: "running",
    connectedApps: ["Notion", "Slack", "Gmail"],
    actionsThisWeek: 31,
    costThisMonth: 1.95,
    lastActive: "8 min ago",
    createdAt: "2026-01-25",
    totalActions: 892,
    totalCost: 14.56,
    sparklineData: [6, 4, 8, 10, 6, 7, 5],
    nextAction: "Draft blog post outline",
    nextActionTime: "In 1 hour",
  },
  {
    id: "agent-7",
    name: "Data Enricher",
    role: "Data Enrichment",
    status: "running",
    connectedApps: ["HubSpot", "Clearbit", "Slack"],
    actionsThisWeek: 56,
    costThisMonth: 3.12,
    lastActive: "1 min ago",
    createdAt: "2026-02-05",
    totalActions: 2341,
    totalCost: 22.30,
    sparklineData: [8, 12, 9, 14, 11, 8, 13],
    nextAction: "Enrich new contacts from HubSpot",
    nextActionTime: "In 15 min",
  },
  {
    id: "agent-8",
    name: "Meeting Scheduler",
    role: "Calendar Management",
    status: "idle",
    connectedApps: ["Google Calendar", "Gmail", "HubSpot"],
    actionsThisWeek: 12,
    costThisMonth: 0.78,
    lastActive: "45 min ago",
    createdAt: "2026-02-12",
    totalActions: 445,
    totalCost: 5.89,
    sparklineData: [2, 3, 1, 4, 2, 3, 1],
    nextAction: "Schedule demo with TechCorp",
    nextActionTime: "Tomorrow 2pm",
  },
]

export const pendingApprovals: Approval[] = [
  {
    id: "appr-1",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    agentRole: "Lead Nurturer",
    riskLevel: "medium",
    status: "pending",
    actionDescription: "Ready to send a personalized follow-up email to Sarah Chen at Acme Corp, who downloaded our whitepaper 3 days ago",
    draftSubject: "Quick thought on your AI operations, Sarah",
    draftContent: "Hi Sarah,\n\nI noticed you grabbed our guide on scaling AI agents. Most teams we work with find that the hardest part isn't the AI itself — it's the approval bottleneck.\n\nWould 15 minutes this week work to show you how we've solved that?\n\nBest,\nThe OpsConductor Team",
    targetEntity: "Sarah Chen, Acme Corp",
    targetType: "contact",
    timestamp: "5 min ago",
    app: "Gmail",
  },
  {
    id: "appr-2",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    agentRole: "Churn Rescue",
    riskLevel: "high",
    status: "pending",
    actionDescription: "Ready to send a 20% discount offer to Globex Inc, who has been inactive for 60 days and has a $4,800 ARR contract",
    draftSubject: "We miss you, Globex. Here's 20% off.",
    draftContent: "Hi team,\n\nWe noticed your usage has dropped significantly. We'd love to understand what changed and help get you back on track.\n\nAs a gesture, we're offering 20% off your next renewal.\n\nLet's chat?",
    targetEntity: "Globex Inc",
    targetType: "company",
    timestamp: "12 min ago",
    app: "Gmail",
  },
  {
    id: "appr-3",
    agentId: "agent-3",
    agentName: "Invoice Chaser",
    agentRole: "Invoice Chaser",
    riskLevel: "low",
    status: "pending",
    actionDescription: "Ready to send a friendly payment reminder for Invoice #INV-2847 ($1,200) to Initech, overdue by 7 days",
    draftSubject: "Friendly reminder: Invoice #INV-2847",
    draftContent: "Hi there,\n\nJust a quick reminder that Invoice #INV-2847 for $1,200 was due last week. If you've already sent payment, please disregard this note.\n\nThanks!",
    targetEntity: "Initech, Invoice #INV-2847",
    targetType: "invoice",
    timestamp: "28 min ago",
    app: "Gmail",
  },
  {
    id: "appr-4",
    agentId: "agent-6",
    agentName: "Content Writer",
    agentRole: "Content Generation",
    riskLevel: "medium",
    status: "pending",
    actionDescription: "Ready to publish draft blog post 'AI Agents in RevOps: A Practical Guide' to Notion workspace",
    draftSubject: "AI Agents in RevOps: A Practical Guide",
    draftContent: "# AI Agents in RevOps\n\nRevenue operations teams are discovering that AI agents can automate repetitive tasks while keeping humans in the loop for high-stakes decisions...",
    targetEntity: "Notion — Blog Workspace",
    targetType: "document",
    timestamp: "18 min ago",
    app: "Notion",
  },
  {
    id: "appr-5",
    agentId: "agent-7",
    agentName: "Data Enricher",
    agentRole: "Data Enrichment",
    riskLevel: "high",
    status: "pending",
    actionDescription: "Wants to update 47 HubSpot contacts with enriched company data from Clearbit — includes revenue and employee count fields",
    targetEntity: "47 HubSpot Contacts",
    targetType: "bulk-update",
    timestamp: "6 min ago",
    app: "HubSpot",
  },
]

export const recentApprovals: Approval[] = [
  {
    id: "appr-10",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    agentRole: "Lead Nurturer",
    riskLevel: "low",
    status: "approved",
    actionDescription: "Sent welcome email to Marcus Webb after HubSpot form submission",
    targetEntity: "Marcus Webb",
    targetType: "contact",
    timestamp: "1 hour ago",
    app: "Gmail",
  },
  {
    id: "appr-11",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    agentRole: "Churn Rescue",
    riskLevel: "medium",
    status: "rejected",
    actionDescription: "Proposed Slack message to #sales about at-risk account Vandelay Industries",
    targetEntity: "Vandelay Industries",
    targetType: "company",
    timestamp: "2 hours ago",
    app: "Slack",
  },
  {
    id: "appr-12",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    agentRole: "Lead Nurturer",
    riskLevel: "low",
    status: "auto-executed",
    actionDescription: "Updated HubSpot contact stage for Priya Sharma to 'Engaged'",
    targetEntity: "Priya Sharma",
    targetType: "contact",
    timestamp: "3 hours ago",
    app: "HubSpot",
  },
  {
    id: "appr-13",
    agentId: "agent-8",
    agentName: "Meeting Scheduler",
    agentRole: "Calendar Management",
    riskLevel: "low",
    status: "approved",
    actionDescription: "Scheduled 30-minute demo call with Raj Patel from TechCorp via Google Calendar",
    targetEntity: "Raj Patel, TechCorp",
    targetType: "meeting",
    timestamp: "4 hours ago",
    app: "Google Calendar",
  },
  {
    id: "appr-14",
    agentId: "agent-6",
    agentName: "Content Writer",
    agentRole: "Content Generation",
    riskLevel: "low",
    status: "auto-executed",
    actionDescription: "Created draft outline for Q2 product update email",
    targetEntity: "Notion — Drafts",
    targetType: "document",
    timestamp: "5 hours ago",
    app: "Notion",
  },
  {
    id: "appr-15",
    agentId: "agent-7",
    agentName: "Data Enricher",
    agentRole: "Data Enrichment",
    riskLevel: "medium",
    status: "approved",
    actionDescription: "Enriched 23 new contacts with Clearbit company data and updated HubSpot records",
    targetEntity: "23 HubSpot Contacts",
    targetType: "bulk-update",
    timestamp: "6 hours ago",
    app: "HubSpot",
  },
]

export const activityEvents: ActivityEvent[] = [
  {
    id: "evt-1",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "HubSpot",
    action: "Checked for new trial signups",
    target: "HubSpot Contacts",
    status: "success",
    cost: 0.001,
    timestamp: "2 min ago",
    reasoning: "Agent checked HubSpot for contacts in Trial stage inactive > 5 days. Found 3 contacts. Queued follow-up emails for Sarah Chen, Marcus Webb, Priya Sharma.",
  },
  {
    id: "evt-2",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    app: "Stripe",
    action: "Detected MRR drop for Globex Inc",
    target: "Globex Inc",
    status: "success",
    cost: 0.002,
    timestamp: "12 min ago",
    reasoning: "Detected 35% usage drop for Globex Inc over 30 days. Flagged as high churn risk. Queued discount offer for approval.",
  },
  {
    id: "evt-3",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "Gmail",
    action: "Sent follow-up email",
    target: "Marcus Webb",
    status: "success",
    cost: 0.003,
    timestamp: "1 hour ago",
  },
  {
    id: "evt-4",
    agentId: "agent-3",
    agentName: "Invoice Chaser",
    app: "Stripe",
    action: "Checked overdue invoices",
    target: "Stripe Invoices",
    status: "success",
    cost: 0.001,
    timestamp: "3 hours ago",
    reasoning: "Queried Stripe for invoices overdue > 7 days. Found 1 invoice: #INV-2847 for Initech ($1,200). Queued payment reminder.",
  },
  {
    id: "evt-5",
    agentId: "agent-5",
    agentName: "Deal Nudger",
    app: "HubSpot",
    action: "Failed to update deal stage",
    target: "Vandelay Industries Deal",
    status: "failed",
    cost: 0.001,
    timestamp: "1 hour ago",
    reasoning: "Attempted to update deal stage from 'Proposal' to 'Negotiation'. HubSpot API returned 403 Forbidden. OAuth token may have expired.",
  },
  {
    id: "evt-6",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    app: "HubSpot",
    action: "Updated contact risk score",
    target: "Acme Corp",
    status: "success",
    cost: 0.001,
    timestamp: "2 hours ago",
  },
  {
    id: "evt-7",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "Slack",
    action: "Posted daily lead summary to #sales",
    target: "#sales channel",
    status: "success",
    cost: 0.002,
    timestamp: "4 hours ago",
  },
  {
    id: "evt-8",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "HubSpot",
    action: "Updated contact stage to Engaged",
    target: "Priya Sharma",
    status: "success",
    cost: 0.001,
    timestamp: "5 hours ago",
  },
  {
    id: "evt-9",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    app: "Gmail",
    action: "Sent check-in email",
    target: "Soylent Corp",
    status: "success",
    cost: 0.003,
    timestamp: "6 hours ago",
  },
  {
    id: "evt-10",
    agentId: "agent-3",
    agentName: "Invoice Chaser",
    app: "Gmail",
    action: "Sent payment reminder",
    target: "Hooli, Invoice #INV-2801",
    status: "success",
    cost: 0.003,
    timestamp: "Yesterday",
  },
  {
    id: "evt-11",
    agentId: "agent-7",
    agentName: "Data Enricher",
    app: "HubSpot",
    action: "Enriched 12 new contacts with Clearbit data",
    target: "HubSpot Contacts",
    status: "success",
    cost: 0.024,
    timestamp: "25 min ago",
    reasoning: "Detected 12 new contacts without enrichment data. Queried Clearbit for firmographic info. Successfully enriched all 12 records.",
  },
  {
    id: "evt-12",
    agentId: "agent-6",
    agentName: "Content Writer",
    app: "Notion",
    action: "Created blog post draft",
    target: "AI Agents in RevOps: A Practical Guide",
    status: "success",
    cost: 0.018,
    timestamp: "35 min ago",
    reasoning: "Generated a 1,200-word blog post draft based on Q2 content calendar. Used product positioning docs and competitor analysis as context.",
  },
  {
    id: "evt-13",
    agentId: "agent-8",
    agentName: "Meeting Scheduler",
    app: "Google Calendar",
    action: "Scheduled demo call",
    target: "Raj Patel, TechCorp",
    status: "success",
    cost: 0.002,
    timestamp: "45 min ago",
    reasoning: "Found mutual availability between sales rep and prospect. Booked 30-min Zoom call for Thursday at 2pm EST.",
  },
  {
    id: "evt-14",
    agentId: "agent-7",
    agentName: "Data Enricher",
    app: "Clearbit",
    action: "Resolved company domain for new lead",
    target: "jennifer.wu@nexatech.io",
    status: "success",
    cost: 0.003,
    timestamp: "52 min ago",
  },
  {
    id: "evt-15",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "HubSpot",
    action: "Moved lead to MQL stage",
    target: "David Park, Synthwave Labs",
    status: "success",
    cost: 0.001,
    timestamp: "1 hour ago",
    reasoning: "Lead scoring threshold crossed after 3 website visits and whitepaper download. Updated lifecycle stage from Lead to MQL.",
  },
  {
    id: "evt-16",
    agentId: "agent-6",
    agentName: "Content Writer",
    app: "Slack",
    action: "Shared content calendar update",
    target: "#marketing channel",
    status: "success",
    cost: 0.001,
    timestamp: "1.5 hours ago",
  },
  {
    id: "evt-17",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    app: "Stripe",
    action: "Detected failed payment",
    target: "Initech — Invoice #INV-3021",
    status: "success",
    cost: 0.001,
    timestamp: "2 hours ago",
    reasoning: "Stripe webhook indicated failed payment. Card on file expired. Flagged for follow-up and queued dunning email.",
  },
  {
    id: "evt-18",
    agentId: "agent-8",
    agentName: "Meeting Scheduler",
    app: "Gmail",
    action: "Sent meeting confirmation",
    target: "Lisa Huang, CloudFirst",
    status: "success",
    cost: 0.002,
    timestamp: "2 hours ago",
  },
  {
    id: "evt-19",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "Gmail",
    action: "Sent personalized case study",
    target: "Tom Anderson, Blueshift Inc",
    status: "success",
    cost: 0.004,
    timestamp: "2.5 hours ago",
    reasoning: "Contact visited pricing page 3 times. Selected the RevOps case study based on industry match (SaaS) and sent personalized email.",
  },
  {
    id: "evt-20",
    agentId: "agent-7",
    agentName: "Data Enricher",
    app: "HubSpot",
    action: "Updated company revenue data",
    target: "Acme Corp",
    status: "success",
    cost: 0.002,
    timestamp: "3 hours ago",
  },
  {
    id: "evt-21",
    agentId: "agent-3",
    agentName: "Invoice Chaser",
    app: "Slack",
    action: "Notified finance team of overdue invoice",
    target: "#finance — Globex Invoice #INV-2990",
    status: "success",
    cost: 0.001,
    timestamp: "3 hours ago",
    reasoning: "Invoice #INV-2990 ($3,400) is 14 days overdue. Escalated to #finance per rules (>10 days overdue).",
  },
  {
    id: "evt-22",
    agentId: "agent-6",
    agentName: "Content Writer",
    app: "Notion",
    action: "Updated product changelog",
    target: "Notion — Product Updates",
    status: "success",
    cost: 0.008,
    timestamp: "3.5 hours ago",
  },
  {
    id: "evt-23",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    app: "Slack",
    action: "Posted weekly churn risk report",
    target: "#cs-alerts channel",
    status: "success",
    cost: 0.004,
    timestamp: "4 hours ago",
    reasoning: "Weekly report. 4 accounts with >25% usage drop MoM: Globex Inc, Soylent Corp, Massive Dynamic, Wayne Enterprises.",
  },
  {
    id: "evt-24",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "HubSpot",
    action: "Created new deal",
    target: "NexaTech — Enterprise Pilot",
    status: "success",
    cost: 0.002,
    timestamp: "4 hours ago",
  },
  {
    id: "evt-25",
    agentId: "agent-8",
    agentName: "Meeting Scheduler",
    app: "Google Calendar",
    action: "Rescheduled meeting",
    target: "Demo with Acme Corp",
    status: "success",
    cost: 0.001,
    timestamp: "5 hours ago",
    reasoning: "Acme Corp requested reschedule via email. Found next available slot and sent updated calendar invite.",
  },
  {
    id: "evt-26",
    agentId: "agent-7",
    agentName: "Data Enricher",
    app: "Clearbit",
    action: "Bulk enrichment job completed",
    target: "23 new contacts",
    status: "success",
    cost: 0.046,
    timestamp: "6 hours ago",
    reasoning: "23/23 contacts enriched. Added company size, industry, revenue range, and social profiles.",
  },
  {
    id: "evt-27",
    agentId: "agent-5",
    agentName: "Deal Nudger",
    app: "Slack",
    action: "Sent stale deal alert",
    target: "#sales — Pied Piper deal stale 15 days",
    status: "success",
    cost: 0.001,
    timestamp: "6 hours ago",
  },
  {
    id: "evt-28",
    agentId: "agent-3",
    agentName: "Invoice Chaser",
    app: "Stripe",
    action: "Verified payment received",
    target: "Cyberdyne Systems, Invoice #INV-2756",
    status: "success",
    cost: 0.001,
    timestamp: "7 hours ago",
    reasoning: "Payment of $2,850 confirmed via Stripe webhook. Marked invoice as paid. Sent thank-you confirmation.",
  },
  {
    id: "evt-29",
    agentId: "agent-6",
    agentName: "Content Writer",
    app: "Gmail",
    action: "Drafted customer success email",
    target: "Quarterly review — Wayne Enterprises",
    status: "success",
    cost: 0.006,
    timestamp: "8 hours ago",
  },
  {
    id: "evt-30",
    agentId: "agent-2",
    agentName: "Churn Rescue",
    app: "HubSpot",
    action: "Updated NPS risk indicators",
    target: "14 accounts scored",
    status: "success",
    cost: 0.003,
    timestamp: "9 hours ago",
    reasoning: "Processed NPS survey responses. 14 accounts scored. 3 flagged as detractors (score < 7). Queued personalized outreach.",
  },
  {
    id: "evt-31",
    agentId: "agent-8",
    agentName: "Meeting Scheduler",
    app: "Gmail",
    action: "Sent meeting prep briefing",
    target: "Sales team — Globex Inc meeting",
    status: "success",
    cost: 0.005,
    timestamp: "10 hours ago",
    reasoning: "Compiled account context: recent support tickets, product usage, renewal date, and stakeholder map.",
  },
  {
    id: "evt-32",
    agentId: "agent-1",
    agentName: "Lead Nurturer",
    app: "HubSpot",
    action: "Imported webinar attendees",
    target: "42 new leads from Q2 webinar",
    status: "success",
    cost: 0.008,
    timestamp: "Yesterday",
    reasoning: "Imported 42 attendees from 'Scaling AI Ops' webinar. Created contacts, tagged source, and queued follow-up sequences.",
  },
  {
    id: "evt-33",
    agentId: "agent-7",
    agentName: "Data Enricher",
    app: "HubSpot",
    action: "Deduplicated contact records",
    target: "8 duplicate contacts merged",
    status: "success",
    cost: 0.003,
    timestamp: "Yesterday",
  },
  {
    id: "evt-34",
    agentId: "agent-5",
    agentName: "Deal Nudger",
    app: "HubSpot",
    action: "Updated deal forecast",
    target: "Q2 pipeline — $142K weighted",
    status: "success",
    cost: 0.002,
    timestamp: "Yesterday",
    reasoning: "Recalculated Q2 forecast based on deal stage probabilities and activity signals. Total weighted pipeline: $142K across 8 deals.",
  },
  {
    id: "evt-35",
    agentId: "agent-3",
    agentName: "Invoice Chaser",
    app: "Gmail",
    action: "Sent final payment notice",
    target: "Massive Dynamic, Invoice #INV-2688",
    status: "success",
    cost: 0.003,
    timestamp: "Yesterday",
    reasoning: "Invoice #INV-2688 ($5,200) is 28 days overdue. Sent final notice. Next step: flag for collections if no response in 72 hours.",
  },
]

export const integrations: Integration[] = [
  { id: "int-1", name: "Gmail", icon: "Mail", category: "Email", connected: true, status: "live", lastSynced: "2 min ago", agentCount: 3 },
  { id: "int-2", name: "HubSpot", icon: "BarChart3", category: "CRM", connected: true, status: "live", lastSynced: "5 min ago", agentCount: 3 },
  { id: "int-3", name: "Stripe", icon: "CreditCard", category: "Finance", connected: true, status: "live", lastSynced: "12 min ago", agentCount: 2 },
  { id: "int-4", name: "Slack", icon: "MessageSquare", category: "Messaging", connected: true, status: "live", lastSynced: "1 min ago", agentCount: 4 },
  { id: "int-5", name: "Notion", icon: "FileText", category: "Productivity", connected: true, status: "expiring", lastSynced: "1 hour ago", agentCount: 1 },
  { id: "int-6", name: "Clearbit", icon: "Search", category: "Enrichment", connected: true, status: "live", lastSynced: "30 min ago", agentCount: 1 },
  { id: "int-7", name: "Google Calendar", icon: "Calendar", category: "Calendar", connected: true, status: "live", lastSynced: "15 min ago", agentCount: 1 },
  { id: "int-8", name: "Salesforce", icon: "Cloud", category: "CRM", connected: false },
  { id: "int-9", name: "Outlook", icon: "Mail", category: "Email", connected: false },
  { id: "int-10", name: "Teams", icon: "MessageSquare", category: "Messaging", connected: false },
  { id: "int-11", name: "QuickBooks", icon: "Calculator", category: "Finance", connected: false },
  { id: "int-12", name: "Airtable", icon: "Table", category: "Productivity", connected: false },
  { id: "int-13", name: "Google Sheets", icon: "Sheet", category: "Productivity", connected: false },
  { id: "int-14", name: "Calendly", icon: "CalendarClock", category: "Calendar", connected: false },
  { id: "int-15", name: "Jira", icon: "Kanban", category: "Project Management", connected: false },
  { id: "int-16", name: "Linear", icon: "Layers", category: "Project Management", connected: false },
]

export const cockpitStats = {
  totalActionsThisWeek: 180,
  actionsTrend: +18,
  revenueInfluenced: 28750,
  pendingApprovals: 5,
  agentCostThisMonth: 10.74,
}
